
1. Collate the following informations for every 36 states in Nigeria.
     1. State Name 
     2. State Capital 
     3. State Population 
     4. State Landmass
2. Create a Pandas Series object of state population and landmass using state name as the key of both. 
3. From the two Series objects, create a DataFrame object and add the state capital as new column to the table. 
4. Calculate the population density of each state and use it to generate a new column on the DataFrame object.

In [1]:
import numpy as np
import pandas as pd

In [3]:
state = ['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi',
        'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 
        'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe','Zamfara']
capital = ['Umuahia', 'Yola', 'Uyo', 'Awka', 'Bauchi', 'Yenagoa', 'Makurdi', 'Maiduguri', 'Calabar', 'Asaba', 'Abakaliki', 
           'Benin City', 'Ado Ekiti', 'Enugu',  'Abuja', 'Gombe', 'Owerri', 'Dutse', 'Kaduna', 'Kano', 'Katsina', 'Birnin Kebbi',
           'Lokoja', 'Ilorin', 'Ikeja', 'Lafia', 'Minna', 'Abeokuta', 'Akure', 'Oshogbo', 'Ibadan', 'Jos', 'Port Harcourt', 
           'Sokoto', 'Jalingo', 'Damaturu', 'Gusau']
population = [2845370, 3178950, 3902051, 4177828, 4653066, 1704515, 4253641, 4171104, 2882988, 4112445, 2176947, 3233366, 
              2398357, 3267837, 1405201, 2365040, 3927563, 4361002, 6113503, 9401288, 5801584, 3256541, 3314043, 2365353,
              9113605, 1869377, 3954772, 3751140, 3460877, 3416959, 5580894, 3206531, 5198716, 3702676, 2294800, 2321339, 
              3278873]
Landmass = [6320, 36917, 7081, 4844, 49119, 10773, 34059, 70898, 20156, 17698, 5670, 17802, 6353, 7161, 7315, 18768,
            5530, 23154, 46053, 20131, 24192, 36800, 29833, 36825, 3345, 27117, 76363, 16762, 15500, 9251, 28454, 30913,
            11077, 25973, 54473, 45502, 39762]
pop = pd.Series(population, index = state)
pop.head()

Abia         2845370
Adamawa      3178950
Akwa Ibom    3902051
Anambra      4177828
Bauchi       4653066
dtype: int64

In [4]:
land = pd.Series(Landmass, index = state)
land.head()

Abia          6320
Adamawa      36917
Akwa Ibom     7081
Anambra       4844
Bauchi       49119
dtype: int64

In [5]:
sd = pd.DataFrame({'Capital':capital, 'population':pop})
sd.head()

           Capital  population
Abia       Umuahia     2845370
Adamawa       Yola     3178950
Akwa Ibom      Uyo     3902051
Anambra       Awka     4177828
Bauchi      Bauchi     4653066

In [13]:
sd['Landmass'] = land
sd.head()

           Capital  population  Landmass
Abia       Umuahia     2845370      6320
Adamawa       Yola     3178950     36917
Akwa Ibom      Uyo     3902051      7081
Anambra       Awka     4177828      4844
Bauchi      Bauchi     4653066     49119

In [15]:
sd['population density'] = sd['population'] / sd['Landmass']
sd.head()

           Capital  population  Landmass  population density
Abia       Umuahia     2845370      6320          450.216772
Adamawa       Yola     3178950     36917           86.110735
Akwa Ibom      Uyo     3902051      7081          551.059314
Anambra       Awka     4177828      4844          862.474814
Bauchi      Bauchi     4653066     49119           94.730471

In [21]:
# sd.to_csv('Nigeria state and population.csv')
pd.read_csv('Nigeria state and population.csv')

     Unnamed: 0        Capital  population  Landmass  population density
0          Abia        Umuahia     2845370      6320          450.216772
1       Adamawa           Yola     3178950     36917           86.110735
2     Akwa Ibom            Uyo     3902051      7081          551.059314
3       Anambra           Awka     4177828      4844          862.474814
4        Bauchi         Bauchi     4653066     49119           94.730471
5       Bayelsa        Yenagoa     1704515     10773          158.221016
6         Benue        Makurdi     4253641     34059          124.890367
7         Borno      Maiduguri     4171104     70898           58.832464
8   Cross River        Calabar     2882988     20156          143.033737
9         Delta          Asaba     4112445     17698          232.367782
10       Ebonyi      Abakaliki     2176947      5670          383.941270
11          Edo     Benin City     3233366     17802          181.629367
12        Ekiti      Ado Ekiti     2398357      6353          377.515662
13        Enugu          Enugu     3267837      7161          456.338081
14          FCT          Abuja     1405201      7315          192.098565
15        Gombe          Gombe     2365040     18768          126.014493
16          Imo         Owerri     3927563      5530          710.228391
17       Jigawa          Dutse     4361002     23154          188.347672
18       Kaduna         Kaduna     6113503     46053          132.749289
19         Kano           Kano     9401288     20131          467.005514
20      Katsina        Katsina     5801584     24192          239.814153
21        Kebbi   Birnin Kebbi     3256541     36800           88.492962
22         Kogi         Lokoja     3314043     29833          111.086481
23        Kwara         Ilorin     2365353     36825           64.232261
24        Lagos          Ikeja     9113605      3345         2724.545590
25     Nasarawa          Lafia     1869377     27117           68.937456
26        Niger          Minna     3954772     76363           51.789113
27         Ogun       Abeokuta     3751140     16762          223.788331
28         Ondo          Akure     3460877     15500          223.282387
29         Osun        Oshogbo     3416959      9251          369.361042
30          Oyo         Ibadan     5580894     28454          196.137415
31      Plateau            Jos     3206531     30913          103.727590
32       Rivers  Port Harcourt     5198716     11077          469.325269
33       Sokoto         Sokoto     3702676     25973          142.558657
34       Taraba        Jalingo     2294800     54473           42.127292
35         Yobe       Damaturu     2321339     45502           51.016197
36      Zamfara          Gusau     3278873     39762           82.462477